### ISSUE TITLE
Very few optimal feature genes selected

### ISSUE THREAD

**Issue by SHADJIA** [prabhakarlab/DUBStepR#3]
Hello admins,

I'm a master's student and I have project work to delineate minimum number of genes which characterize cell subsets. I use Seurat for scRNAseq data analysis. I read your article about DUBStepR package. I have different datasets and I tried your tool, as you describe in your vignette, on our CD4 T cells dataset. Initially, I have 32508 genes in the count matrix. As you suggest, I extract the count matrix from the "data" slot of seurat object after QC analysis, to perform the DUBStepR function. Finally I get only 12 genes as optimal feature genes.

What do you think about the result? I don't get a similar UMAP as one I got using 2000 HVGs of Seurat.

Thank you in advance for your advice.

Regards,
Sha

**Comment by bbbranjan** [comment]
Hi @SHADJIA , thank you for reaching out! Yes, this is a result we have encountered previously. Since the density index (DI) assumes discrete cell clusters in a dataset, there are scenarios where DUBStepR picks a very small subset of genes because that was the only feature set with discrete clusters in feature space. This characteristic of DI has allowed us to find new insights into a dataset (see Figure 6 of the [manuscript](https://www.nature.com/articles/s41467-021-26085-2)). It is expected that the UMAP would be different from that obtained with 2000 HVGs from Seurat. I would recommend annotating the subclusters you get in the UMAP with the 12 DUBStepR feature genes first to see if any interesting clusters appear. 

It would also be beneficial to have a less stringent feature set that allows cells to exist in a loose blob in feature space, especially in your case of CD4+ T cell subclustering, where cell subsets tend to have more subtle and continuous variation rather than sharp, discrete variations usually observed between major cell types. To select a larger feature set using DUBStepR, you can use the `dubStepR.out$corr.info$feature.genes` slot, which contains a vector of feature genes having a correlation range z-score above the minimum threshold. This feature set should get you closer to the result you obtained using 2000 HVGs of Seurat.

The clustering results using the 3 feature sets (using 12-gene DUBStepR, all-gene DUBStepR and 2000-gene HVG) would give you different ways of analysing and visualising the same dataset, and could all inform your final subtype annotations. 

Please feel free to reach out again if anything is unclear, or if you'd like any further assistance :)

**Comment by SHADJIA** [comment]
Hello BBRanjan,

First of all, thanks a lot for your quick and explained reply. 
I annotated the clusters with SingleR (in -built reference) and I find the major type of cells (Monocyte, DC, BM, Tcells,etc.)
As you suggest, I used the genes list from `dubStepR.out$corr.info$feature.genes` slot (around 600 genes) and I get a similar UMAP. 

Thank you once again.

Best,
Sha
