### ISSUE TITLE
Scale data with all genes

### ISSUE THREAD

**Issue by SHADJIA** [prabhakarlab/DUBStepR#4]
Hello BBranjan,

I follow your vignette to select features for my scRNAseq analysis. During the cell clustering, why do you precise the features to be all genes of Seurat object in scale data step (`seuratObj <- ScaleData(seuratObj, features = rownames(seuratObj))`)? Can't it be default, which means the selected features with DUBStepR (set as variable features)?

Thank you in advance for your explanation.

Regards,
Sha

**Comment by bbbranjan** [comment]
Hi @SHADJIA, you're right - the default scaling is only usually done on the variable features. Here, the reason I scaled all genes is because I knew I would be plotting a heatmap of the scaled gene expression in a future step, and wanted to save time by scaling all the genes at once. A more efficient strategy would be to scale only the feature genes during clustering, and later scale only the genes to be plotted in the heatmap. This would give you the same results as in the vignette and would save computational resources.

**Comment by SHADJIA** [comment]
@bbbranjan Thanks for explaining!
